name: tbm

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      default:
        aliases:
          - frontend
